# Generated by Django 4.0.4 on 2022-04-17 22:09

import booksmain.Validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('ISBN', models.IntegerField(validators=[booksmain.Validators.ISBN_validator])),
                ('num_pages', models.IntegerField()),
                ('book_img', models.URLField()),
                ('book_language', models.CharField(max_length=255)),
            ],
        ),
    ]
